CREATE SCHEMA app;

CREATE TABLE app.s_users (
    id    serial PRIMARY KEY,
    email text NOT NULL
);

CREATE TABLE app.id_users (
    id    bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email text NOT NULL
);

CREATE TABLE app.bd_users (
    id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text NOT NULL
);
