//! Raw declarations for `libpg_query`'s C entry points.
//!
//! Generated by `bindgen` from the vendored `pg_query.h` at build time and
//! included here. The allow-list below is for generated code only: C naming
//! conventions do not survive Rust's lints, and there is no version of this file
//! that both matches the header and satisfies `pedantic`.

#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    missing_docs,
    unsafe_code,
    clippy::all,
    clippy::pedantic,
    clippy::nursery,
    reason = "bindgen output: C declarations, generated verbatim from pg_query.h"
)]

include!(concat!(env!("OUT_DIR"), "/ffi.rs"));
