CREATE SCHEMA app;
CREATE PUBLICATION p1 FOR ALL TABLES;
CREATE PUBLICATION p2 FOR ALL TABLES;
CREATE SUBSCRIPTION s
    CONNECTION 'host=replica.example.com dbname=app user=repl password=${REPL_PWD}'
    PUBLICATION p1;
