//! `Column` and column-level features (identity, generated, default, collation).

use serde::{Deserialize, Serialize};

use crate::identifier::{Identifier, QualifiedName};
use crate::ir::column_type::ColumnType;
use crate::ir::default_expr::DefaultExpr;
use crate::ir::difference::Difference;
use crate::ir::eq::{diff_field, Diff};

/// A table column.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Column {
    /// Column name.
    pub name: Identifier,
    /// Canonical column type.
    pub ty: ColumnType,
    /// `NOT NULL` lives here, not in `Constraint`.
    pub nullable: bool,
    /// Optional column default.
    pub default: Option<DefaultExpr>,
    /// Identity specification (`GENERATED ALWAYS|BY DEFAULT AS IDENTITY`).
    pub identity: Option<Identity>,
    /// Generated-column specification (`GENERATED ALWAYS AS (expr) STORED`).
    pub generated: Option<Generated>,
    /// Optional collation.
    pub collation: Option<QualifiedName>,
    /// Optional comment.
    pub comment: Option<String>,
}

/// `GENERATED ... AS IDENTITY` specification.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Identity {
    /// `ALWAYS` or `BY DEFAULT`.
    pub kind: IdentityKind,
    /// Backing sequence options.
    pub sequence: SequenceOptions,
}

/// Identity kind.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum IdentityKind {
    /// `GENERATED ALWAYS AS IDENTITY`.
    Always,
    /// `GENERATED BY DEFAULT AS IDENTITY`.
    ByDefault,
}

/// `GENERATED ALWAYS AS (expr) STORED` specification.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Generated {
    /// Stored vs virtual (PG only supports stored as of v17).
    pub kind: GeneratedKind,
    /// Generation expression.
    pub expression: crate::ir::default_expr::NormalizedExpr,
}

/// Generated-column kind.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum GeneratedKind {
    /// `STORED`.
    Stored,
}

/// Sequence options that back an identity column.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SequenceOptions {
    /// Start value.
    pub start: i64,
    /// Increment.
    pub increment: i64,
    /// Min value (`None` = type minimum).
    pub min_value: Option<i64>,
    /// Max value (`None` = type maximum).
    pub max_value: Option<i64>,
    /// Cache size.
    pub cache: i64,
    /// Whether the sequence cycles.
    pub cycle: bool,
}

impl Diff for Column {
    fn diff(&self, other: &Self) -> Vec<Difference> {
        let mut out = Vec::new();
        out.extend(diff_field("name", &self.name, &other.name));
        out.extend(diff_field(
            "ty",
            &self.ty.render_sql(),
            &other.ty.render_sql(),
        ));
        out.extend(diff_field("nullable", &self.nullable, &other.nullable));
        out.extend(diff_field(
            "default",
            &format!("{:?}", self.default),
            &format!("{:?}", other.default),
        ));
        out.extend(diff_field(
            "identity",
            &format!("{:?}", self.identity),
            &format!("{:?}", other.identity),
        ));
        out.extend(diff_field(
            "generated",
            &format!("{:?}", self.generated),
            &format!("{:?}", other.generated),
        ));
        out.extend(diff_field(
            "collation",
            &format!("{:?}", self.collation),
            &format!("{:?}", other.collation),
        ));
        out.extend(diff_field(
            "comment",
            &format!("{:?}", self.comment),
            &format!("{:?}", other.comment),
        ));
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn id(s: &str) -> Identifier {
        Identifier::from_unquoted(s).unwrap()
    }

    fn base() -> Column {
        Column {
            name: id("email"),
            ty: ColumnType::Text,
            nullable: false,
            default: None,
            identity: None,
            generated: None,
            collation: None,
            comment: None,
        }
    }

    #[test]
    fn equal_columns_have_no_diff() {
        assert!(base().canonical_eq(&base()));
    }

    #[test]
    fn type_change_diffs() {
        let mut b = base();
        b.ty = ColumnType::Varchar { len: Some(255) };
        assert!(base().diff(&b).iter().any(|x| x.path == "ty"));
    }

    #[test]
    fn nullability_change_diffs() {
        let mut b = base();
        b.nullable = true;
        assert!(base().diff(&b).iter().any(|x| x.path == "nullable"));
    }

    #[test]
    fn identity_change_diffs() {
        let mut b = base();
        b.identity = Some(Identity {
            kind: IdentityKind::ByDefault,
            sequence: SequenceOptions {
                start: 1,
                increment: 1,
                min_value: None,
                max_value: None,
                cache: 1,
                cycle: false,
            },
        });
        assert!(base().diff(&b).iter().any(|x| x.path == "identity"));
    }
}
