//! Reloptions generators (v0.3.3) and column-level storage/compression.
//!
//! Range-bounded strategies prevent generating PG-invalid combinations.

#![allow(clippy::needless_pass_by_value)]

use proptest::prelude::*;

use pgevolve_core::ir::canon::filter_pg_defaults::type_default_storage;
use pgevolve_core::ir::column::{Compression, StorageKind};
use pgevolve_core::ir::column_type::ColumnType;
use pgevolve_core::ir::reloptions::{
    AutovacuumOptions, IndexStorageOptions, NotNanF64, TableStorageOptions,
};

/// Generate a random `STORAGE` strategy that is type-aware.
///
/// Toastable types (those whose PG default is not `PLAIN`) may be assigned
/// any of the four storage variants. Fixed-width types (default `PLAIN`) only
/// yield `None` or `Some(PLAIN)` — the others are illegal for those types.
pub(super) fn arb_storage(ty: &ColumnType) -> BoxedStrategy<Option<StorageKind>> {
    let is_toastable = !matches!(type_default_storage(ty), StorageKind::Plain);
    if is_toastable {
        prop_oneof![
            Just(None),
            Just(Some(StorageKind::Plain)),
            Just(Some(StorageKind::External)),
            Just(Some(StorageKind::Extended)),
            Just(Some(StorageKind::Main)),
        ]
        .boxed()
    } else {
        prop_oneof![Just(None), Just(Some(StorageKind::Plain))].boxed()
    }
}

/// Generate a random `COMPRESSION` strategy that is type-aware.
///
/// Postgres rejects `COMPRESSION` on column types that aren't TOAST-able
/// (`column data type X does not support compression`). Mirrors
/// [`arb_storage`]: toastable types may carry any compression codec or
/// `None`; fixed-width types only yield `None`.
pub(super) fn arb_compression(ty: &ColumnType) -> BoxedStrategy<Option<Compression>> {
    let is_toastable = !matches!(type_default_storage(ty), StorageKind::Plain);
    if is_toastable {
        prop_oneof![
            Just(None),
            Just(Some(Compression::Pglz)),
            Just(Some(Compression::Lz4)),
        ]
        .boxed()
    } else {
        Just(None).boxed()
    }
}

/// Generate 0–3 populated autovacuum option fields.
///
/// Uses `NotNanF64::new` which returns `Ok` for all finite floats; the range
/// `0.0..1.0` never produces NaN, so the `unwrap` carries a justifying comment
/// matching the style used throughout this module for literal-bounded inputs.
fn arb_autovacuum_options() -> impl Strategy<Value = AutovacuumOptions> {
    (
        prop_oneof![Just(None), Just(Some(true)), Just(Some(false))], // enabled
        prop_oneof![Just(None), (0u64..1000).prop_map(Some)],         // vacuum_threshold
        // 0.0..1.0 is never NaN — unwrap is safe.
        prop_oneof![
            Just(None),
            (0.0f64..1.0).prop_map(|f| Some(NotNanF64::new(f).unwrap())),
        ], // vacuum_scale_factor
    )
        .prop_map(
            |(enabled, vacuum_threshold, vacuum_scale_factor)| AutovacuumOptions {
                enabled,
                vacuum_threshold,
                vacuum_scale_factor,
                ..Default::default()
            },
        )
}

/// Generate random [`TableStorageOptions`] with 0–3 fields set.
///
/// fillfactor range 10..=100 matches PG's documented valid range for tables.
pub(super) fn arb_table_storage() -> impl Strategy<Value = TableStorageOptions> {
    (
        prop_oneof![Just(None), (10u32..=100).prop_map(Some)], // fillfactor
        arb_autovacuum_options(),
        prop_oneof![Just(None), (0u32..=64).prop_map(Some)], // parallel_workers
    )
        .prop_map(
            |(fillfactor, autovacuum, parallel_workers)| TableStorageOptions {
                fillfactor,
                autovacuum,
                parallel_workers,
                ..Default::default()
            },
        )
}

/// Generate random [`IndexStorageOptions`] with 0–2 fields set.
///
/// fillfactor range 50..=100 is B-tree–safe (the only method generated by
/// `arbitrary_indexes_for_table`). fastupdate is randomly toggled.
pub(super) fn arb_index_storage() -> impl Strategy<Value = IndexStorageOptions> {
    (
        prop_oneof![Just(None), (50u32..=100).prop_map(Some)], // fillfactor (B-tree range)
        prop_oneof![Just(None), Just(Some(true)), Just(Some(false))], // fastupdate
    )
        .prop_map(|(fillfactor, fastupdate)| IndexStorageOptions {
            fillfactor,
            fastupdate,
            ..Default::default()
        })
}
